version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /bin/sh -c "python manage.py seed && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/:/usr/src/backend/
      - ./backend/logs/:/usr/src/backend/logs/
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=os&tq#n3-#+fbidohzpp+!vxxw%ia^r=28eho%53r5rwo30y=b
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=breakthecode
      - SQL_USER=breakthecode
      - SQL_PASSWORD=breakthecode
      - SQL_HOST=db
      - SQL_PORT=5432
      - DEBUG=0
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=breakthecode
      - POSTGRES_PASSWORD=breakthecode
      - POSTGRES_DB=breakthecode

volumes:
  postgres_data: